[env:ble_micro_pro]
platform = nordicnrf52@10.12.0
board = adafruit_feather_nrf52840
framework = arduino
platform_packages = toolchain-gccarmnoneeabi@1.140201.0
board_build.ldscript = nrf52840_s140_v6.ld
build_flags =
  -D CFG_DEBUG=0
monitor_speed = 115200

extra_scripts = post:tools/copy_uf2.py
